name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix: { dir: ['./tictactoe', './hangman'] }

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install CMake
              run: |
                  sudo apt-get update
                  sudo apt-get install cmake

            - name: Install gtest
              run: |
                  sudo apt-get install libgtest-dev
                  cd /usr/src/gtest
                  sudo cmake CMakeLists.txt
                  sudo make
                  sudo cp lib/*.a /usr/lib

            - name: Build executable
              working-directory: ${{ matrix.dir }}
              run: |
                  mkdir build
                  cd build
                  cmake -DBUILD_EXEC=ON ..
                  cmake --build .

            - name: Run unit tests
              working-directory: ${{ matrix.dir }}
              run: |
                  mkdir test
                  cd test
                  cmake -DUNIT_TEST=ON ..
                  cmake --build .
                  ./runTests

